### ISSUE TITLE
 How to start Simod

### ISSUE THREAD

**Issue by dcy652701** [AutomatedProcessImprovement/Simod#131]
I tried to start the Simod. But I didn't see the default config file. I copied from README.md. 

First I got a versioin error, it said the version must be 2, but the README.md is 4. 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.cache/pypoetry/virtualenvs/simod-CiydOZFs-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/simod-CiydOZFs-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/simod-CiydOZFs-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/simod-CiydOZFs-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/simod-CiydOZFs-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/Simod/src/simod/cli.py", line 40, in optimize
    settings = Configuration.from_path(config_path)
  File "/usr/src/Simod/src/simod/configuration.py", line 618, in from_path
    return Configuration.from_stream(f)
  File "/usr/src/Simod/src/simod/configuration.py", line 613, in from_stream
    return Configuration.from_yaml(config)
  File "/usr/src/Simod/src/simod/configuration.py", line 582, in from_yaml
    assert config['version'] == 2, 'Configuration version must be 2'
AssertionError: Configuration version must be 2

Then I change the version into 2, I got another problem:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.cache/pypoetry/virtualenvs/simod-CiydOZFs-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/simod-CiydOZFs-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/simod-CiydOZFs-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/simod-CiydOZFs-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/simod-CiydOZFs-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/Simod/src/simod/cli.py", line 40, in optimize
    settings = Configuration.from_path(config_path)
  File "/usr/src/Simod/src/simod/configuration.py", line 618, in from_path
    return Configuration.from_stream(f)
  File "/usr/src/Simod/src/simod/configuration.py", line 613, in from_stream
    return Configuration.from_yaml(config)
  File "/usr/src/Simod/src/simod/configuration.py", line 584, in from_yaml
    common_settings = CommonSettings.from_dict(config['common'])
  File "/usr/src/Simod/src/simod/configuration.py", line 213, in from_dict
    log_path = Path(config['log_path'])
KeyError: 'log_path'

**Comment by iharsuvorau** [comment]
Hi, not all parts of README.md are in sync at the moment. Configuration in README.md is newer than the version of Simod mentioned there. Just use the newer version of Simod for the Docker container. 

You can run Simod using the following commands (assuming zsh):

```zsh
docker run -it --rm -v `pwd`/resources/:/usr/src/Simod/resources nokal/simod:3.5.25 bash
# in container
Xvfb :99 &>/dev/null & disown
poetry run simod optimize --config_path resources/config/sample.yml
```
