### ISSUE TITLE
BPIC_2017 running with fuzzy resource profiles and extraneous discovery method switched to naive fails

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/Simod#152]
Hi @david-chapela, our last benchmarking failed on BPIC 2017 (Call Center hasn't been executed too because of that). Below are the details, the configuration and traceback. Would you like to take a look? Otherwise, I'm taking it after I finish with Simod HTTP.

```yaml
version: 4
common:
  train_log_path: /usr/src/Simod/input/logs/BPIC_2017_train.csv.gz
  test_log_path: /usr/src/Simod/input/logs/BPIC_2017_test.csv.gz
  num_final_evaluations: 10
  evaluation_metrics:
    - 3_gram_distance
    - 2_gram_distance
    - absolute_event_distribution
    - relative_event_distribution
    - circadian_event_distribution
    - arrival_event_distribution
    - cycle_time_distribution
  log_ids:
    case: case_id
    activity: activity
    resource: resource
    start_time: start_time
    end_time: end_time
    enabled_time: enabled_time
preprocessing:
  multitasking: false
  enable_time_concurrency_threshold: 0.5
  concurrency_df: 0.75
  concurrency_l2l: 0.9
  concurrency_l1l: 0.9
control_flow:
  optimization_metric: n_gram_distance
  num_iterations: 30
  num_evaluations_per_iteration: 5
  gateway_probabilities: discovery
  discovery_algorithm: sm1
  epsilon:
    - 0.1
    - 1.0
  eta:
    - 0.2
    - 0.6
  replace_or_joins:
    - true
    - false
  prioritize_parallelism:
    - true
    - false
resource_model:
  optimization_metric: circadian_event_distribution
  num_iterations: 40
  num_evaluations_per_iteration: 5
  resource_profiles:
    discovery_type: differentiated_fuzzy
    granularity:
      - 15
      - 60
    fuzzy_angle:
      - 0.1
      - 0.9
extraneous_activity_delays:
  optimization_metric: relative_event_distribution
  num_iterations: 20
  discovery_method: naive
```

Trace:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/Simod/src/simod/cli.py", line 36, in optimize
    simod.run()
  File "/usr/src/Simod/src/simod/simod.py", line 144, in run
    timers = self.optimize_extraneous_activity_delays()
  File "/usr/src/Simod/src/simod/simod.py", line 274, in optimize_extraneous_activity_delays
    timers = self._extraneous_delays_optimizer.run()
  File "/usr/src/Simod/src/simod/extraneous_delays/optimizer.py", line 56, in run
    enhancer.enhance_simulation_model_with_delays()
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/extraneous_activity_delays/enhance_with_delays.py", line 162, in enhance_simulation_model_with_delays
    best_result = fmin(
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 540, in fmin
    return trials.fmin(
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/hyperopt/base.py", line 671, in fmin
    return fmin(
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 586, in fmin
    rval.exhaust()
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 300, in run
    self.serial_evaluate()
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 178, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/hyperopt/base.py", line 892, in evaluate
    rval = self.fn(pyll_rval)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/extraneous_activity_delays/enhance_with_delays.py", line 216, in _enhancement_iteration
    distance_value = self._evaluate_iteration(enhanced_simulation_model, output_folder, alphas, scaled_timers)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/extraneous_activity_delays/enhance_with_delays.py", line 272, in _evaluate_iteration
    sim_out = simulate_prosimos(
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/extraneous_activity_delays/prosimos/simulator.py", line 40, in simulate
    run_simulation(
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/prosimos/simulation_engine.py", line 617, in run_simulation
    return run_simpy_simulation(
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/prosimos/simulation_engine.py", line 632, in run_simpy_simulation
    execute_full_process(bpm_env, fixed_starting_times)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/prosimos/simulation_engine.py", line 537, in execute_full_process
    bpm_env.execute_enabled_event(current_event)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/prosimos/simulation_engine.py", line 170, in execute_enabled_event
    completed_at, completed_datetime = self.execute_task(c_event)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/prosimos/simulation_engine.py", line 211, in execute_task
    full_evt = TaskEvent(
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/prosimos/execution_info.py", line 53, in __init__
    self.real_duration = bpm_env.sim_setup.real_task_duration(self.ideal_duration, self.resource_id,
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/prosimos/simulation_setup.py", line 132, in real_task_duration
    return self.calendars_map[self.resources_map[resource_id].calendar_id].find_idle_time(
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/pix_framework/discovery/resource_calendar_and_performance/crisp/resource_calendar.py", line 571, in find_idle_time
    worked_time, total_time = self._find_time_starting(pending_duration, c_day, c_date)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/pix_framework/discovery/resource_calendar_and_performance/crisp/resource_calendar.py", line 659, in _find_time_starting
    return pending_duration, self._find_time_completion(pending_duration, available_duration, c_day, from_date)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/pix_framework/discovery/resource_calendar_and_performance/crisp/resource_calendar.py", line 680, in _find_time_completion
    total_duration -= self.work_intervals[c_day][i].duration
IndexError: list index out of range
```

In the trace, we can see that the extraneous package uses CRISP profiles, while Simod was running using FUZZY profiles. Could it be the reason? However, Academic Credentials and BPIC 2012 finished ok.

This issue can be related to pix-framework, extraneous, or prosimos. There's an option to transfer this issue to another repository on the right sidebar.

**Comment by david-chapela** [comment]
Hi @iharsuvorau, we actually never tried this case because the tests of Fuzzy+Extraneous we run were without optimization (in extraneous delays), so Prosimos wasn't being called within this package.

I don't have much time these days, could you take a look at it? I checked the code and the simulation model (including the specific fuzzy parameters) are being passed correctly to the _ExtraneousDelays_ package, so I can't easily see a reason why it would run the Crisp version of Prosimos.

Key points in the workflow of how it works:
- In [here](https://github.com/AutomatedProcessImprovement/Simod/blob/2c9b81e4d1aac6865ed6efca1009bfdcf3d5ca37/src/simod/extraneous_delays/optimizer.py#L53) Simod creates the SimulationModel instance that ExtraneousDelays uses, and puts there the simulation parameters (using `._to_prosimos_format()` function [here](https://github.com/AutomatedProcessImprovement/Simod/blob/2c9b81e4d1aac6865ed6efca1009bfdcf3d5ca37/src/simod/extraneous_delays/optimizer.py#L79)).
- I've checked, and this function DOES add the `model_type: "FUZZY"` to these `dict` with the parameters, so it should be fine.
- Then ExtraneousDelays package enhances these parameters by adding the _timer events_ modeling the delays in [here](https://github.com/AutomatedProcessImprovement/extraneous-activity-delays/blob/05f3c51e5f0daedd16b2230c404cdd44a6d19d49/src/extraneous_activity_delays/enhance_with_delays.py#L208). However, [this](https://github.com/AutomatedProcessImprovement/extraneous-activity-delays/blob/05f3c51e5f0daedd16b2230c404cdd44a6d19d49/src/extraneous_activity_delays/prosimos/simulation_model_enhancer.py#L39) just adds an extra field, so should be fine too.
- Then, it [simulates](https://github.com/AutomatedProcessImprovement/extraneous-activity-delays/blob/05f3c51e5f0daedd16b2230c404cdd44a6d19d49/src/extraneous_activity_delays/enhance_with_delays.py#L272) with Prosimos with these parameters [dumped](https://github.com/AutomatedProcessImprovement/extraneous-activity-delays/blob/05f3c51e5f0daedd16b2230c404cdd44a6d19d49/src/extraneous_activity_delays/enhance_with_delays.py#L244) in a file.

My idea would be to check the parameters file of one of these _ExtraneousDelays_ iterations (debugging) and see if it has the `model_type = "FUZZY"` element just to be sure that the _json_ file is correct. If Prosimos is running Crisp I would imagine that at some place we are missing this `model_type = "FUZZY"`, but can't imagine where without debugging.

**Comment by david-chapela** [comment]
@iharsuvorau I just checked running it in local and checking the JSON files, and the parameters are Crisp, I don't really understand how it is happening, if you can take a look at it. The JSON files are:
- In all iterations of _Control-flow_ optimization: Fuzzy.
- In all iterations of _ResourceModel_ optimization: Fuzzy.
- In the first iteration of _ExtraneousDelay_: Crisp.

Something is happening in the call to `._to_prosimos_format()` when preparing the _ExtraneousDelayOptimizer_.

**Comment by iharsuvorau** [comment]
Hi @orlenyslp. We're having an issue with Simod and its dependencies. So far, it seems the issue is the one we once discussed with you, when CRISP calendar discovery (that we moved to `pix-framework` repo) had been calculating negative duration, remember?

This is the place where it's happening, https://github.com/AutomatedProcessImprovement/pix-framework/blob/main/src/pix_framework/discovery/resource_calendar_and_performance/crisp/resource_calendar.py#L680C13-L680C13.

Here's the screenshot from the debugger with parameters, because this bug isn't so easy to reproduce:
<img width="1254" alt="image" src="https://github.com/AutomatedProcessImprovement/Simod/assets/6259054/de5256ce-e817-4691-b920-fc9a35f5ea02">

You can see, the `total_duration` is negative. Is it correct behavior for the CRISP calendar discovery? You've been fixing this bug before, right?

**Comment by iharsuvorau** [comment]
@orlenyslp However, the bug we're facing is probably a different one, though, in the same function.

On the screenshot below, we can see that `i = -3` when `self.work_intervals[c_day]` length is only 2 items. When the function tries to get `self.work_intervals[c_day][-3]` it's actually trying to get the third result from the end of the list. Is it an expected behavior?

<img width="1259" alt="Screenshot 2023-09-05 at 17 32 40" src="https://github.com/AutomatedProcessImprovement/Simod/assets/6259054/81a1a4dc-c01f-4a18-9804-419c7ed87a8b">

**Comment by david-chapela** [comment]
@iharsuvorau yeah, it took me a while to get to see that it was because of how we read the `ResourceModel`. I was first checking all the files, and all of them were good.

Don't worry about the benchmarks of previous weeks, the extraneous delays were not optimized in those cases (we were running the direct optimization), so there should be no difference in the result. I think it only affected this last run where we optimize the `ExtraneousDelays` with 20 iterations.
