### ISSUE TITLE
Benchmarking of RC2 v3.2.0 with extraneous timers optimization after calendars optimization

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/Simod#82]
Event logs:

* BPIC_2012_W_contained (train, test)
* BPIC_2017_W_contained (train, test)
* ConsultaDataMining201618 (train, test)
* Governmental_Agency (train, test)
* poc_processmining (train, test)
* Production (train, test)

**Comment by iharsuvorau** [comment]
* Governmental_Agency finishes with `ValueError: probabilities are not non-negative` reported by Prosimos (this log failed during the previous benchmarking because the time ran out, this time I use another machine for benchmarking, not HPC)

Still running most of the other logs.

**Comment by iharsuvorau** [comment]
Also, this time I'm facing a new issue with most of the runs. Before, I ran experiments via SLURM on HPC. Now, it's a simple powerful Linux machine in UT network, and I run experiments with a Python script executing a Simod's Docker container on a Simod configuration file via Python's `subprocess.run`. 

I'm having the following issue now:

```
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/src/Simod/src/simod/simulation/prosimos.py", line 252, in _evaluate_logs_using_metrics
    value = compute_metric(metric, validation_log, validation_log_ids, simulated_log, simulated_log_ids)
  File "/usr/src/Simod/src/simod/metrics/metrics.py", line 31, in compute_metric
    result = get_dl(event_log_1, event_log_1_ids, event_log_2, event_log_2_ids)
  File "/usr/src/Simod/src/simod/metrics/metrics.py", line 106, in get_dl
    return evaluator.measure_distance()
  File "/usr/src/Simod/src/simod/metrics/tsd_evaluator.py", line 64, in measure_distance
    distance = self._evaluate_seq_distance(self.log_data, self.simulation_data)
  File "/usr/src/Simod/src/simod/metrics/tsd_evaluator.py", line 86, in _evaluate_seq_distance
    pool = Pool(processes=cpu_count)
  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
"""
```

With this explanation https://stackoverflow.com/questions/51485212/multiprocessing-gives-assertionerror-daemonic-processes-are-not-allowed-to-have, it seems that because of the _multithreaded_ evaluation which wants to run _also multithreaded_ TSD (DL) metric computation it can't, because a thread cannot start another pool of threads.

There's a solution to this, https://stackoverflow.com/questions/6974695/python-process-pool-non-daemonic. But it still doesn't seem correct for a thread to run another pool of threads. It can actually slow down the metric computation because of a race for resources.

**Comment by iharsuvorau** [comment]
Hi @david-chapela. I'm still running benchmarking, but I've just taken BPIC 2012 to peak into the results.

![BPIC_2012_W_contained_test, BPIC_2012-abs_hourly_emd-resource-timers, BPIC_2012-abs_hourly_emd-resource - Work-in-Progress (WIP) data](https://user-images.githubusercontent.com/6259054/208944816-0eb0351a-f5f7-4540-9c30-ca52c6896d0a.png)

![BPIC_2012_W_contained_test, BPIC_2012-abs_hourly_emd-resource-timers, BPIC_2012-abs_hourly_emd-resource - Activity instances over time data](https://user-images.githubusercontent.com/6259054/208944835-6bfa0178-be86-408e-8d5b-f11a8d37c782.png)

With timers, graphs look way off. However, average cycle time seems to be closer to the original times.

**Comment by iharsuvorau** [comment]
These are the results after the bug is fixed (we've already reviewed them, so this is just for the history):

![Production_test, Production-abs_hourly_emd-resource-timers-2, Production-abs_hourly_emd-resource - Work-in-Progress (WIP) data](https://user-images.githubusercontent.com/6259054/209828945-2800d874-bd78-40dd-af27-5365b0c7bdee.png)

![Production_test, Production-abs_hourly_emd-resource-timers-2, Production-abs_hourly_emd-resource - Activity instances over time data](https://user-images.githubusercontent.com/6259054/209829084-82effaae-990e-4b6d-b299-224ebf24ffca.png)

<img width="1548" alt="Screenshot 2022-12-22 at 19 22 40" src="https://user-images.githubusercontent.com/6259054/209829111-5605e1fd-0115-4fc6-bca5-2f6104fb6bf9.png">

[Production-timers_evaluation_20221222_160233267754.csv](https://github.com/AutomatedProcessImprovement/Simod/files/10314759/Production-timers_evaluation_20221222_160233267754.csv)

[Production-no-timers_evaluation_20221130_180242945366.csv](https://github.com/AutomatedProcessImprovement/Simod/files/10314761/Production-no-timers_evaluation_20221130_180242945366.csv)

**Comment by iharsuvorau** [comment]
We decided:

* To compare the results when optimizing for extraneous timers BEFORE the calendar optimization
* To use absolute EMD instead of cycle time EMD in the extraneous package as an optimization metric
